modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
[[mods]] #mandatory
modId="untitledmess" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="1.0.0" #mandatory
displayName="Untitled Mess" #mandatory
authors="Oliviafrostpaw" 
# The description text for the mod (multi line!) (#mandatory)
description='''
Testing mod for shinanigans
'''
[[dependencies.untitledmess]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.untitledmess]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
